sudo: required
language: java
services: docker

env:
  - ANDROID_BUILD_TOOLS=26.0.3
  - ANDROID_BUILD_TOOLS=27.0.3

before_install: cd build-tools-jdk8-alpine

install: true

script: docker build --build-arg "ANDROID_BUILD_TOOLS=${ANDROID_BUILD_TOOLS}" -t "androidsdk:${ANDROID_BUILD_TOOLS}-jdk8-alpine" .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME"/"androidsdk:${ANDROID_BUILD_TOOLS}-jdk8-alpine"